### PR TITLE
Add hyphenation and text appearance options for EPUBs

### PR DESCRIPTION
**Pull request by AbeJellinek**

### CODE REVIEW

**Comment by mrtcode** [comment]
It works well!

**Comment by dstillman** [comment]
Is `<input type="range"`…styleable? 

Screenshot 2024-06-19 at 4 54 56 AM

At the very least, we'll want to style the popup a bit (@yexingsha).

We should probably steal a few things [from Apple](https://github.com/zotero/zotero/issues/4252#issue-2357741447), including showing numbers and centering character and word spacing at 0%.

**Comment by yexingsha** [comment]
I think the range and step of these settings are a bit too large. Let's try these values:
- Line height: 0.80–2.50, step=0.05
- Word spacing: -100%–100%, step=5%
- Letter spacing: -0.1em–0.1em, step=0.005em (display it as %)

I was thinking of ditching the x button, and then remembered we kept the x in the search popup because of split view, and then found that in split view, clicking the x of the popup in the inactive view can close/open the popup in the active view. But that's probably not a worthwhile problem to solve, since I can't think of any use case where people would want to have different text appearances in split view. So maybe we just keep to one single popup for split view, and let it control both? Then we can remove the x button, and enable it to be closed by clicking outside its bounds, which is in line with [apple's recommendation](https://developer.apple.com/design/human-interface-guidelines/popovers).

Also, I think putting this button next to the reset zoom button would make more sense, since in EPUB reader the zoom buttons basically control text appearance.

Regarding styling, we can either use the native slider appearance of macOS and windows, in light and dark mode:

popup-epub-mac
popup-epub-win

popup-epub-mac-dark
popup-epub-win-dark

Or we can come up with our own slider styling for all platforms. I guess using the interface native look would be more in line with our overall approach, but one single style would be easier to implement and maintain? (This question also concerns a few other 'unstyled' controls littered throughout the interface: the slider in the ink annotation color picker menu, as well the checkboxes in reader search box and note editor search box)

**Comment by yexingsha** [comment]
Looks good! Just need to set font size to 13px (this is an issue for reader UI in general), move the popup under the button, and update the labels:

Screenshot 2024-06-20 at 22 57 36

**Comment by yexingsha** [comment]
Oh right, I forgot to switch back. Thanks!

**Comment by yexingsha** [comment]
Looks good to me!

**Pull request merged**
